// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-courses.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^4.4.3";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.110.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv(["SUPABASE_PUBLISHABLE_KEY", "VITE_SUPABASE_PUBLISHABLE_KEY"]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-courses.ts
var list_courses_default = defineTool({
  name: "list_courses",
  title: "Listar cursos",
  description: "Lista os cursos publicados da Tropa Cient\xEDfica, com trilha, n\xEDvel, dura\xE7\xE3o e se s\xE3o gratuitos. Aceita busca por texto.",
  inputSchema: {
    search: z.string().trim().nullable().describe("Texto opcional para filtrar por t\xEDtulo."),
    limit: z.number().int().nullable().describe("M\xE1ximo de cursos retornados (padr\xE3o 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("courses").select("id, slug, title, summary, level, duration_min, is_free, status, trail_id, instructor_name").eq("status", "published").order("order_index", { ascending: true }).limit(Math.min(Math.max(limit ?? 25, 1), 100));
    if (search) query = query.ilike("title", `%${search}%`);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { courses: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-course.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^4.4.3";
var get_course_default = defineTool2({
  name: "get_course",
  title: "Detalhar curso",
  description: "Retorna um curso publicado pelo slug, com m\xF3dulos e aulas (t\xEDtulo, tipo, dura\xE7\xE3o e se \xE9 pr\xE9via gratuita).",
  inputSchema: {
    slug: z2.string().trim().min(1).describe("Slug do curso, ex.: 'metodologia-cientifica'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ slug }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data: course, error } = await supabase.from("courses").select(
      "id, slug, title, summary, description, level, duration_min, is_free, status, requirements, target_audience, learning_objectives, instructor_name"
    ).eq("slug", slug).eq("status", "published").maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!course) return { content: [{ type: "text", text: `Curso n\xE3o encontrado: ${slug}` }], isError: true };
    const { data: modules, error: modulesError } = await supabase.from("modules").select("id, title, description, order_index, lessons(id, slug, title, content_type, duration_sec, order_index, is_preview)").eq("course_id", course.id).order("order_index", { ascending: true });
    if (modulesError) return { content: [{ type: "text", text: modulesError.message }], isError: true };
    const payload = { course, modules: modules ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(payload) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/my-progress.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
var my_progress_default = defineTool3({
  name: "my_progress",
  title: "Meu progresso",
  description: "Lista as matr\xEDculas do usu\xE1rio autenticado e o progresso em cada curso (percentual e aulas conclu\xEDdas).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const userId = ctx.getUserId();
    const [enrollments, progress] = await Promise.all([
      supabase.from("enrollments").select("id, scope, course_id, trail_id, status, access_type, granted_at, expires_at").eq("user_id", userId),
      supabase.from("course_progress").select("course_id, pct_complete, lessons_completed, lessons_total, completed_at, updated_at").eq("user_id", userId)
    ]);
    const failure = enrollments.error ?? progress.error;
    if (failure) return { content: [{ type: "text", text: failure.message }], isError: true };
    const payload = { enrollments: enrollments.data ?? [], progress: progress.data ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(payload) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/my-certificates.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
var my_certificates_default = defineTool4({
  name: "my_certificates",
  title: "Meus certificados",
  description: "Lista os certificados emitidos para o usu\xE1rio autenticado, com c\xF3digo de valida\xE7\xE3o, curso, carga hor\xE1ria e situa\xE7\xE3o.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("certificates").select("certificate_code, course_title, trail_name, student_name, hours, issuer, status, issued_at, pdf_url").eq("user_id", ctx.getUserId()).order("issued_at", { ascending: false });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { certificates: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/verify-certificate.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^4.4.3";
var verify_certificate_default = defineTool5({
  name: "verify_certificate",
  title: "Validar certificado",
  description: "Valida um certificado da Tropa Cient\xEDfica pelo c\xF3digo p\xFAblico e retorna aluno, curso, carga hor\xE1ria e situa\xE7\xE3o.",
  inputSchema: {
    certificate_code: z3.string().trim().min(3).describe("C\xF3digo impresso no certificado.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ certificate_code }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("public_certificates").select("certificate_code, student_name, course_title, trail_name, issuer, hours, issued_at, status, revoked_at").eq("certificate_code", certificate_code).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) {
      return { content: [{ type: "text", text: `Nenhum certificado encontrado para o c\xF3digo ${certificate_code}.` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { certificate: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "dptdoprxjusyeirmygbb";
var mcp_default = defineMcp({
  name: "tropa-cientifica",
  title: "Tropa Cient\xEDfica",
  version: "0.1.0",
  instructions: "Ferramentas da plataforma Tropa Cient\xEDfica. Use `list_courses` e `get_course` para explorar o cat\xE1logo de cursos e aulas, `my_progress` para o progresso do usu\xE1rio autenticado, `my_certificates` para os certificados dele e `verify_certificate` para validar um c\xF3digo de certificado.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_courses_default, get_course_default, my_progress_default, my_certificates_default, verify_certificate_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
