-- Lock down pg_net so only the backend (service_role) can invoke HTTP calls
REVOKE ALL ON ALL FUNCTIONS IN SCHEMA net FROM PUBLIC;
REVOKE ALL ON ALL FUNCTIONS IN SCHEMA net FROM anon;
REVOKE ALL ON ALL FUNCTIONS IN SCHEMA net FROM authenticated;
REVOKE USAGE ON SCHEMA net FROM PUBLIC;
REVOKE USAGE ON SCHEMA net FROM anon;
REVOKE USAGE ON SCHEMA net FROM authenticated;

GRANT USAGE ON SCHEMA net TO service_role;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA net TO service_role;

ALTER DEFAULT PRIVILEGES IN SCHEMA net REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC, anon, authenticated;